version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NEXT_PUBLIC_LIVEKIT_URL=${NEXT_PUBLIC_LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
    depends_on:
      - agent

  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    depends_on:
      - chatterbox
    expose:
      - "8000"
    environment:
      - PORT=8000
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - TRANSCRIPT_REDIS_URL=${TRANSCRIPT_REDIS_URL}
      - CHATTERBOX_URL=http://chatterbox:8001
      - CHATTERBOX_VOICE_ID=${CHATTERBOX_VOICE_ID}
    volumes:
      - ./chatterbox/voices:/app/voices

  chatterbox:
    build:
      context: ./chatterbox
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./chatterbox/voices:/app/voices
      - ./chatterbox/model_cache:/root/.cache/huggingface
    environment:
      - MODEL_CACHE_DIR=/root/.cache/huggingface
      - HF_HOME=/root/.cache/huggingface
      # - DEFAULT_VOICE_PROMPT_PATH=/app/voices/KrishnaDas.wav
      - USE_CUSTOM_VOICE_PROMPT=false

networks:
  default:
    name: ahoum-agent-net