version: "3.9"

services:

  agent:
    build:
      context: .
      dockerfile: agent/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - TRANSCRIPT_REDIS_URL=${TRANSCRIPT_REDIS_URL}
      - SPEECHIFY_API_KEY=${SPEECHIFY_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - NOTIFY_URL=${NOTIFY_URL}


networks:
  default:
    name: ahoum-agent-net
