version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    expose:
      - "3000"
    environment:
      - PORT=3000
      - NEXT_PUBLIC_LIVEKIT_URL=${NEXT_PUBLIC_LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
    depends_on:
      - agent
    networks:
      - ahoum-agent-net

  agent:
    build:
      context: .
      dockerfile: agent/Dockerfile
    expose:
      - "8000"
    environment:
      - PORT=8000
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING:-mongodb://mongodb:27017/ahoum_db}
    depends_on:
      - mongodb
    networks:
      - ahoum-agent-net
    volumes:
      - ./agent/.env:/app/.env:ro
  
  # Add MongoDB service
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ahoum_db
    networks:
      - ahoum-agent-net
    command: --wiredTigerCacheSizeGB 1

networks:
  ahoum-agent-net:
    driver: bridge

volumes:
  mongodb_data:
