version: "3"

services:
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: 82.29.162.1
      ME_CONFIG_MONGODB_PORT: 5432
      ME_CONFIG_MONGODB_ADMINUSERNAME: ahoum-admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: "Ahoum@654321"
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
